Repository ansible/awx-operator, pull requests merged in 2021-04, with the labels that each got.

#208 Include support for nodeSelector and tolerations in AWX Postgres pod
  README.md
  ansible/templates/crd.yml.j2
  deploy/awx-operator.yaml
  deploy/crds/awx_v1beta1_crd.yaml
  deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
  deploy/olm-catalog/awx-operator/manifests/awx.ansible.com_awxs_crd.yaml
  roles/installer/defaults/main.yml
  roles/installer/templates/tower_postgres.yaml.j2
Labels: enhancement

#214 Expose extra volume config
  README.md
  ansible/templates/crd.yml.j2
  deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
  deploy/olm-catalog/awx-operator/manifests/awx.ansible.com_awxs_crd.yaml
  roles/installer/defaults/main.yml
  roles/installer/templates/tower_deployment.yaml.j2
Labels: documentation, enhancement

#235 Split container image and version in 2 variables
  README.md
  ansible/templates/crd.yml.j2
  deploy/awx-operator.yaml
  deploy/crds/awx_v1beta1_crd.yaml
  deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
  deploy/olm-catalog/awx-operator/manifests/awx.ansible.com_awxs_crd.yaml
  roles/installer/defaults/main.yml
  roles/installer/tasks/main.yml
  roles/installer/templates/tower_deployment.yaml.j2
  roles/installer/templates/tower_postgres.yaml.j2
Labels: breaking_change, component:docs, state:needs_review, type:enhancement

#204 Set Service to use type ClusterIP instead of NodePort when tower_ingress_type is Ingress
  README.md
  ansible/templates/crd.yml.j2
  deploy/awx-operator.yaml
  deploy/crds/awx_v1beta1_crd.yaml
  deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
  deploy/olm-catalog/awx-operator/manifests/awx.ansible.com_awxs_crd.yaml
  roles/installer/templates/tower_service.yaml.j2
Labels: state:needs_review, type:enhancement

#217 Updated logic to validate changes on configmaps, deployments and statefulsets
  roles/installer/tasks/initialize_django.yml
  roles/installer/tasks/main.yml
  roles/installer/tasks/migrate_data.yml
  roles/installer/tasks/resources_configuration.yml
  roles/installer/templates/tower_postgres.yaml.j2
Labels: breaking_change, state:needs_review, state:needs_test, type:bug, type:enhancement

#198 Added support to override PosgreSQL sslmode
  README.md
  roles/installer/tasks/database_configuration.yml
  roles/installer/templates/credentials.py.j2
Labels: state:needs_review, type:enhancement
