Repository ansible/awx-operator, pull requests merged in 2021-06, with the labels that each got.

#330 Introducing service type definition and reworking Ingress rules
  README.md
  ansible/group_vars/all
  ansible/instantiate-awx-deployment.yml
  ansible/templates/crd.yml.j2
  ansible/templates/operator.yml.j2
  deploy/awx-operator.yaml
  deploy/crds/awx_v1beta1_crd.yaml
  deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
  docs/awx-demo.svg
  molecule/test-local/converge.yml
  molecule/test-minikube/converge.yml
  roles/installer/defaults/main.yml
  roles/installer/templates/ingress.yaml.j2
  roles/installer/templates/service.yaml.j2
  scripts/build.sh
Labels: breaking_change

#400 Do not clean up pvc when awxbackup cr is deleted
  roles/backup/templates/backup_pvc.yml.j2
Labels: state:needs_review

#397 Dynamic secret backup & restore
  ansible/templates/awxrestore_crd.yml.j2
  deploy/awx-operator.yaml
  deploy/crds/awxrestore_v1beta1_crd.yaml
  roles/backup/tasks/awx-cro.yml
  roles/backup/tasks/dump_generated_secret.yml
  roles/backup/tasks/dump_secret.yml
  roles/backup/tasks/main.yml
  roles/backup/tasks/secrets.yml
  roles/backup/templates/secrets.yml.j2
  roles/restore/tasks/cleanup.yml
  roles/restore/tasks/deploy_awx.yml
  roles/restore/tasks/postgres.yml
  roles/restore/tasks/secrets.yml
  roles/restore/templates/secrets.yml.j2
  roles/restore/vars/main.yml
Labels: breaking_change

#435 Preserve newlines in AWX spec
  roles/backup/tasks/awx-cro.yml
  roles/restore/tasks/deploy_awx.yml
  roles/restore/templates/awx_object.yml.j2
Labels: breaking_change, state:needs_review
