Repository ansible/awx-operator, pull requests merged in 2024-06, with the labels that each got.

#1676 Add support for horizontal pod autoscaling
  config/crd/bases/awx.ansible.com_awxs.yaml
  docs/user-guide/advanced-configuration/horizontal-pod-autoscaler.md
  docs/user-guide/advanced-configuration/scaling-the-web-and-task-pods-independently.md
  roles/installer/templates/deployments/task.yaml.j2
  roles/installer/templates/deployments/web.yaml.j2
Labels: community

#1846 Fix custom CA certificates for task/web/migration
  roles/installer/templates/deployments/task.yaml.j2
  roles/installer/templates/deployments/web.yaml.j2
  roles/installer/templates/jobs/migration.yaml.j2
Labels: community

#1893 Cast manage_replicas to bool
  roles/installer/templates/deployments/task.yaml.j2
  roles/installer/templates/deployments/web.yaml.j2
Labels: community

#1892 Add scheduling controls to Mesh Ingress
  config/crd/bases/awx.ansible.com_awxmeshingresses.yaml
  config/manifests/bases/awx-operator.clusterserviceversion.yaml
  roles/mesh_ingress/defaults/main.yml
  roles/mesh_ingress/templates/deployment.yml.j2
Labels: community

#1878 Ability to add custom labels to the DB migration pods
  roles/installer/templates/jobs/migration.yaml.j2
Labels: community

#1906 Split metrics utility cronjobs for crc and local report
  roles/installer/tasks/enable_metrics_utility.yml
  roles/installer/tasks/enable_metrics_utility_console.yml
  roles/installer/tasks/install.yml
  roles/installer/templates/cronjobs/metrics-utility-gather.yaml.j2
Labels: debug-3ci

#1900 Add github-actions package manager
  .github/dependabot.yml
Labels: community, dependencies

#1904 Update index.md
  docs/installation/index.md
Labels: community
