Repository ansible/awx-operator, pull requests merged in 2024-03, with the labels that each got.

#1737 fix: correct unsafe conditional
  roles/backup/tasks/secrets.yml
Labels: community

#1745 fix: revert type of status.upgradedPostgresVersion to string
  roles/installer/tasks/update_status.yml
Labels: community

#1674 Add -ness checks and refactor migrations
  config/crd/bases/awx.ansible.com_awxs.yaml
  config/rbac/role.yaml
  docs/user-guide/advanced-configuration/container-probes.md
  roles/installer/tasks/initialize_django.yml
  roles/installer/tasks/install.yml
  roles/installer/tasks/migrate_schema.yml
  roles/installer/tasks/resources_configuration.yml
  roles/installer/tasks/update_status.yml
  roles/installer/templates/deployments/task.yaml.j2
  roles/installer/templates/deployments/web.yaml.j2
  roles/installer/templates/jobs/migration.yaml.j2
Labels: community

#1748 Fix table format in container-probes.md
  docs/user-guide/advanced-configuration/container-probes.md
Labels: community

#1746 add support for defining loadbalancer class
  config/crd/bases/awx.ansible.com_awxs.yaml
  config/manifests/bases/awx-operator.clusterserviceversion.yaml
  docs/user-guide/network-and-tls-configuration.md
  roles/installer/defaults/main.yml
  roles/installer/templates/networking/service.yaml.j2
Labels: community

#1750 Add imagePullSecrets option to Mesh Ingress
  config/crd/bases/awx.ansible.com_awxmeshingresses.yaml
  config/manifests/bases/awx-operator.clusterserviceversion.yaml
  roles/mesh_ingress/defaults/main.yml
  roles/mesh_ingress/templates/deployment.yml.j2
Labels: community

#1740 Bind EE images version with DEFAULT_AWX_VERSION
  docs/user-guide/advanced-configuration/deploying-a-specific-version-of-awx.md
  roles/installer/defaults/main.yml
  roles/installer/tasks/set_images.yml
  roles/mesh_ingress/defaults/main.yml
Labels: community

#1758 add dependabot config to bump doc dependencies
  .github/dependabot.yml
Labels: component:docs, dependencies

#1757 docs: add tips about traefik api groups
  docs/user-guide/advanced-configuration/mesh-ingress.md
Labels: community

#1783 csv: Fix metrics utility fields
  config/manifests/bases/awx-operator.clusterserviceversion.yaml
Labels: community

#1779 docs: add description of init container image definition
  docs/user-guide/advanced-configuration/deploying-a-specific-version-of-awx.md
Labels: community

#1786 fix: correct readinessProbe for web pod
  roles/installer/templates/deployments/web.yaml.j2
Labels: community

#1787 fix: add retries to find running web pod
  roles/installer/tasks/resources_configuration.yml
Labels: community

#1794 Add noxfile and workflow to test docsite PRs
  .github/workflows/ci.yaml
  .github/workflows/reusable-nox.yml
  noxfile.py
Labels: component:docs, community

#1791 postgresql: Cast sorted_old_postgres_pods as list
  roles/installer/tasks/database_configuration.yml
Labels: community
